server:
  port: 8000

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useSSL=true&charset=utf8mb4&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis: # Redis数据库索引（默认为0）
    database: '0'
    host: 127.0.0.1  #Redis服务器地址
    port: 6379  # Redis服务器连接端口
    timeout: 10000 # 连接超时时间（毫秒）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.model

logging:
  level:
    org.example.mapper: debug